-- ============================================================
-- V2 : Sample Data
-- ============================================================
--
-- Historical sample seed data has been removed.
-- The application now relies on a later migration to ensure that
-- only the minimum default company record exists.
