ALTER TABLE executive_receivable
    ADD COLUMN IF NOT EXISTS partner_type VARCHAR(40) NOT NULL DEFAULT 'SALES',
    ADD COLUMN IF NOT EXISTS business_scope VARCHAR(200),
    ADD COLUMN IF NOT EXISTS owner_name VARCHAR(80),
    ADD COLUMN IF NOT EXISTS tax_email VARCHAR(120),
    ADD COLUMN IF NOT EXISTS bank_account VARCHAR(160),
    ADD COLUMN IF NOT EXISTS settlement_terms VARCHAR(200),
    ADD COLUMN IF NOT EXISTS country VARCHAR(80),
    ADD COLUMN IF NOT EXISTS contract_status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    ADD COLUMN IF NOT EXISTS last_contact_date DATE;
