ALTER TABLE payroll_record
    ADD COLUMN IF NOT EXISTS salary_type VARCHAR(20) NOT NULL DEFAULT 'EXCEL',
    ADD COLUMN IF NOT EXISTS annual_salary NUMERIC(15,2) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS hourly_wage NUMERIC(15,2) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS work_days NUMERIC(8,2) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS work_hours NUMERIC(8,2) NOT NULL DEFAULT 0;
